# Goal: I have to do SAST for my code 

name: Code Quality

on: 
    workflow_call:      # you can call this workflow before/after any other workflow

jobs:
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              
            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with: 
                node-version: '24'
                cache: npm
                cache-dependency-path:  frontend/package-lock.json
          
            - name: Install npm packages
              run: npm ci
              working-directory: frontend

            - name: Run Linter
              run: npm run lint  
              working-directory: frontend


            - name: Setup NodeJs
              uses: actions/setup-node@v7
              with: 
                node-version: '24'
                cache: npm
                cache-dependency-path:  backend/package-lock.json

            - name: Install npm packages
              run: npm ci
              working-directory: frontend

            - name: Run Linter
              run: npm run lint  
              working-directory: frontend