# GOal To run the END to END devsecops pipeline 

name: DevSecOps

on: 
    push:
        branches: [main]
       
jobs:

    code-quality:
        uses: ./.github/workflows/code-quality.yml


    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml 

    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

    docker-checks:
        uses:  ./.github/workflows/docker-scans.yml
        secrets: inherit

    sonar_qube:
        uses: ./.github/workflows/sonar-scan.yml 
        secrets: inherit   
    

    code-test:
        uses: ./.github/workflows/code-test.yml

 
    docker-push:
        uses: ./.github/workflows/docker-push.yml
        needs: [code-quality,code-test,sonar_qube,docker-checks,dependency-checks,secret-scanning]
        secrets: inherit   

        